# -*- Mode:Org; Coding:utf-8; fill-column:158 -*-
#+TITLE:       free42 Custom Menus
#+AUTHOR:      Mitch Richling
#+EMAIL:       http://www.mitchr.me/
#+DATE:        2021-03-19
#+DESCRIPTION: Making Custom Menus for the free42/hp-42s/DM42
#+LANGUAGE:    en
#+OPTIONS:     num:t toc:nil \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:t skip:nil d:nil todo:t pri:nil H:5 p:t author:t html-scripts:nil
#+HTML_HEAD: <style>body { width: 95%; margin: 2% auto; font-size: 18px; line-height: 1.4em; font-family: Georgia, serif; color: black; background-color: white; }</style>
#+HTML_HEAD: <style>body { min-width: 500px; max-width: 1024px; }</style>
#+HTML_HEAD: <style>h1,h2,h3,h4,h5,h6 { color: #A5573E; line-height: 1em; font-family: Helvetica, sans-serif; }</style>
#+HTML_HEAD: <style>h1,h2,h3 { line-height: 1.4em; }</style>
#+HTML_HEAD: <style>h1.title { font-size: 3em; }</style>
#+HTML_HEAD: <style>h4,h5,h6 { font-size: 1em; }</style>
#+HTML_HEAD: <style>.org-src-container { border: 1px solid #ccc; box-shadow: 3px 3px 3px #eee; font-family: Lucida Console, monospace; font-size: 80%; margin: 0px; padding: 0px 0px; position: relative; }</style>
#+HTML_HEAD: <style>.org-src-container>pre { line-height: 1.2em; padding-top: 1.5em; margin: 0.5em; background-color: #404040; color: white; overflow: auto; }</style>
#+HTML_HEAD: <style>.org-src-container>pre:before { display: block; position: absolute; background-color: #b3b3b3; top: 0; right: 0; padding: 0 0.2em 0 0.4em; border-bottom-left-radius: 8px; border: 0; color: white; font-size: 100%; font-family: Helvetica, sans-serif;}</style>
#+HTML_HEAD: <style>pre.example { white-space: pre-wrap; white-space: -moz-pre-wrap; white-space: -o-pre-wrap; font-family: Lucida Console, monospace; font-size: 80%; background: #404040; color: white; display: block; padding: 0em; border: 2px solid black; }</style>
#+HTML_LINK_HOME: https://www.mitchr.me/
#+HTML_LINK_UP: https://richmit.github.io/hp42/
#+EXPORT_FILE_NAME: ../docs/custom

#+ATTR_HTML: :border 2 solid #ccc :frame hsides :align center
|        <r> | <l>              |
|  *Author:* | /{{{author}}}/ |
| *Updated:* | /{{{time(%Y-%m-%d %H:%M:%S)}}}/ |
#+ATTR_HTML: :align center
Copyright {{{time(%Y)}}} Mitch Richling. All rights reserved.

#+TOC: headlines 5

#        #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #
#   00   #    10   #    20   #    30   #    40   #    50   #    60   #    70   #    80   #    90   #   100   #   110   #   120   #   130   #   140   #   150   #   160   #
# 234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
#        #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #
#        #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #

* Metadata

This home for this HTML file is: https://richmit.github.io/hp42/custom.html

Files related to this document may be found on github: https://github.com/richmit/hp42

   - =src= directory: Contains the org-mode file that generated this HTML document
   - =docs= directory: Contains this html document
   - =bin= directory: Contains raw program files

* Introduction

The custom menu on the 42s is a wonderful thing, but it is also very limited.  It's just too small!!  And it is only one level deep!!  So instead of simply
assigning functions to the menu keys, how about assigning programs to the keys which present a hierarchical menu of functions?  Coding up such programs is
tedious.  So this org-mode document has a Little bit of Emacs lisp that will consume a table, and generate a 42s program implementing a hierarchical menu.

The flow to create your custom CUST program:
  - Evaluate the "Generic menu generator" babel block in the =hp42s-meta.org= file.  This will define the function =MJR-generate-42-menu-code=
  - Evaluate the "For CUSTOM-type Menus" babel block in the =hp42s-meta.org= file.  This will define the function =MJR-custom-x-gen=
  - Define your menu in the [[Menu Contents][Menu Contents]] section.
  - Evaluate the babel block in the [[Menu Code][Menu Code]] section below.
  - Load the program on your calculator

** Customizing Custom Menu Table

The first column (which I labeled Menu) describes the menu keys.  Colons are used to define a menu hierarchy.  For example "=top:mid:thingy=" means we have a
top level menu "=top=" containing a menu "=mid=" containing a function/program "=thingy=".  Another entry like "=top:thingy2=" would add a function/program
key "=thingy2="to the "=top=" menu -- yes menus can contain a mix of functions/programs and menus.

The only limitation on menu hierarchy depth or size comes from the use of two digit local labels in the generated code.  A label is consume for each
function/program and for each menu page.

The second column is the function/program name/label to call.  If this is empty, then the menu name will be used.  For example "=SFUN:HYP:SINH=" will call the
=SINH= function if no Program is specified.

The other columns of the table are not used.

* Custom Menus

** Menu Contents

#+ATTR_HTML: :rules groups :frame box :align center
#+NAME: cust
| Menu            | Function/Program |                                               |
|-----------------+------------------+-----------------------------------------------|
| SFUN:HYP:SINH   |                  |                                               |
| SFUN:HYP:COSH   |                  |                                               |
| SFUN:HYP:TANH   |                  |                                               |
| SFUN:HYP:ASINH  |                  |                                               |
| SFUN:HYP:ACOSH  |                  |                                               |
| SFUN:HYP:ATANH  |                  |                                               |
|-----------------+------------------+-----------------------------------------------|
| SFUN:L&P:lnYX   |                  | https://richmit.github.io/hp42/math.html      |
| SFUN:L&P:       |                  |                                               |
| SFUN:L&P:Y√X    | YROOT            | https://richmit.github.io/hp42/math.html      |
| SFUN:L&P:Y↑X    |                  |                                               |
| SFUN:L&P:       |                  |                                               |
| SFUN:L&P:       |                  |                                               |
| SFUN:L&P:ln2    |                  | https://richmit.github.io/hp42/math.html      |
| SFUN:L&P:2↑X    |                  | https://richmit.github.io/hp42/math.html      |
| SFUN:L&P:LN     |                  |                                               |
| SFUN:L&P:EXP    |                  |                                               |
| SFUN:L&P:LOG    |                  |                                               |
| SFUN:L&P:10↑X   |                  |                                               |
|-----------------+------------------+-----------------------------------------------|
| SFUN:PERC:%T    |                  | https://richmit.github.io/hp42/math.html      |
| SFUN:PERC:%CH   |                  |                                               |
| SFUN:PERC:%     |                  |                                               |
|-----------------+------------------+-----------------------------------------------|
| SFUN:PROB:COMB  |                  |                                               |
| SFUN:PROB:PERM  |                  |                                               |
| SFUN:PROB:      |                  |                                               |
| SFUN:PROB:GAMMA |                  |                                               |
| SFUN:PROB:BETA  |                  | https://richmit.github.io/hp42/math.html      |
| SFUN:PROB:      |                  |                                               |
| SFUN:PROB:NPDF  |                  | https://richmit.github.io/hp42/math.html      |
| SFUN:PROB:NCDF  |                  | https://richmit.github.io/hp42/math.html      |
|-----------------+------------------+-----------------------------------------------|
| SFUN:INT:IDIV   | BASE÷            |                                               |
| SFUN:INT:MOD    |                  |                                               |
| SFUN:INT:GCD    |                  | https://richmit.github.io/hp42/math.html      |
| SFUN:INT:LCM    |                  | https://richmit.github.io/hp42/math.html      |
| SFUN:INT:FLOR   | FLOOR            | https://richmit.github.io/hp42/math.html      |
| SFUN:INT:CEIL   |                  | https://richmit.github.io/hp42/math.html      |
|-----------------+------------------+-----------------------------------------------|
| SFUN:CPLX:RPART |                  | https://richmit.github.io/hp42/math.html      |
| SFUN:CPLX:IPART |                  | https://richmit.github.io/hp42/math.html      |
| SFUN:CPLX:CONJ  |                  | https://richmit.github.io/hp42/math.html      |
| SFUN:CPLX:CABS  |                  | https://richmit.github.io/hp42/math.html      |
| SFUN:CPLX:CARG  |                  | https://richmit.github.io/hp42/math.html      |
|-----------------+------------------+-----------------------------------------------|
| SFUN:TRIG:HYPOT |                  | https://richmit.github.io/hp42/math.html      |
| SFUN:TRIG:ATN2  | ATAN2            | https://richmit.github.io/hp42/math.html      |
|-----------------+------------------+-----------------------------------------------|
| SFUN:ERR:ERF    |                  | https://richmit.github.io/hp42/math.html      |
| SFUN:ERR:ERFC   |                  | https://richmit.github.io/hp42/math.html      |
| SFUN:ERR:       |                  |                                               |
| SFUN:ERR:NPDF   |                  | https://richmit.github.io/hp42/math.html      |
| SFUN:ERR:NCDF   |                  | https://richmit.github.io/hp42/math.html      |
|-----------------+------------------+-----------------------------------------------|
| MATH:POLY:QEQ   | QUADE            | https://richmit.github.io/hp42/math.html      |
| MATH:POLY:PLYE  |                  | https://richmit.github.io/hp42/math.html      |
| MATH:FMENU      |                  | https://richmit.github.io/hp42/pgmforfun.html |
| MATH:3VEC       |                  | https://richmit.github.io/hp42/math.html      |
|-----------------+------------------+-----------------------------------------------|
| PHIL:PERF       |                  | https://richmit.github.io/hp42/phil.html      |
| PHIL:IMET       |                  | https://richmit.github.io/hp42/phil.html      |
| PHIL:MEAS       |                  | https://richmit.github.io/hp42/meas.html      |
|-----------------+------------------+-----------------------------------------------|
| BASE            |                  | https://richmit.github.io/hp42/base.html      |
| DATE            | DMENU            | https://richmit.github.io/hp42/date.html      |
| CONS            |                  | https://richmit.github.io/hp42/cons.html      |
| UNIT            |                  | https://richmit.github.io/hp42/unit.html      |
| MEAS            |                  | https://richmit.github.io/hp42/meas.html      |
| OPT:SPREF       |                  | https://richmit.github.io/hp42/custom.html    |
| OPT:MKCM        |                  | https://richmit.github.io/hp42/custom.html    |
|-----------------+------------------+-----------------------------------------------|

** Menu Code

The menu program is generated via the following bit of elisp.  You must first define the =MJR-generate-42-menu-code= and =MJR-custom-x-gen= by evaluating the code blocks in the =hp42s-meta.org= file.

#+BEGIN_SRC elisp :var tbl=cust :colnames y :results output verbatum :wrap "src hp42s :tangle yes"
(MJR-generate-42-menu-code "CUST" tbl "stay" "up" #'MJR-custom-x-gen)
#+END_SRC

#+RESULTS:
#+begin_src hp42s :tangle yes
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ (ref:CUST)
@@@@ DSC: Auto-generated menu program
LBL "CUST"
LBL 01            @@@@ Page 1 of menu CUST
CLMENU
"SFUN"
KEY 1 GTO 03
"MATH"
KEY 2 GTO 04
"PHIL"
KEY 3 GTO 05
"BASE"
KEY 4 XEQ 06
"DATE"
KEY 5 XEQ 07
"CONS"
KEY 6 XEQ 08
KEY 7 GTO 02
KEY 8 GTO 02
KEY 9 GTO 00
MENU
STOP
GTO 01
LBL 02            @@@@ Page 2 of menu CUST
CLMENU
"UNIT"
KEY 1 XEQ 09
"MEAS"
KEY 2 XEQ 10
"OPT"
KEY 3 GTO 11
KEY 7 GTO 01
KEY 8 GTO 01
KEY 9 GTO 00
MENU
STOP
GTO 02
LBL 03            @@@@ Page 1 of menu SFUN
CLMENU
"HYP"
KEY 1 GTO 13
"L&P"
KEY 2 GTO 14
"PERC"
KEY 3 GTO 15
"PROB"
KEY 4 GTO 16
"INT"
KEY 5 GTO 17
"CPLX"
KEY 6 GTO 18
KEY 7 GTO 12
KEY 8 GTO 12
KEY 9 GTO 01
MENU
STOP
GTO 03
LBL 12            @@@@ Page 2 of menu SFUN
CLMENU
"TRIG"
KEY 1 GTO 19
"ERR"
KEY 2 GTO 20
KEY 7 GTO 03
KEY 8 GTO 03
KEY 9 GTO 01
MENU
STOP
GTO 12
LBL 13            @@@@ Page 1 of menu HYP
CLMENU
"SINH"
KEY 1 XEQ 21
"COSH"
KEY 2 XEQ 22
"TANH"
KEY 3 XEQ 23
"ASINH"
KEY 4 XEQ 24
"ACOSH"
KEY 5 XEQ 25
"ATANH"
KEY 6 XEQ 26
KEY 9 GTO 03
MENU
STOP
GTO 13
LBL 14            @@@@ Page 1 of menu L&P
CLMENU
"lnYX"
KEY 1 XEQ 28
"Y√X"
KEY 3 XEQ 29
"Y↑X"
KEY 4 XEQ 30
KEY 7 GTO 27
KEY 8 GTO 27
KEY 9 GTO 03
MENU
STOP
GTO 14
LBL 27            @@@@ Page 2 of menu L&P
CLMENU
"ln2"
KEY 1 XEQ 31
"2↑X"
KEY 2 XEQ 32
"LN"
KEY 3 XEQ 33
"EXP"
KEY 4 XEQ 34
"LOG"
KEY 5 XEQ 35
"10↑X"
KEY 6 XEQ 36
KEY 7 GTO 14
KEY 8 GTO 14
KEY 9 GTO 03
MENU
STOP
GTO 27
LBL 15            @@@@ Page 1 of menu PERC
CLMENU
"%T"
KEY 1 XEQ 37
"%CH"
KEY 2 XEQ 38
"%"
KEY 3 XEQ 39
KEY 9 GTO 03
MENU
STOP
GTO 15
LBL 16            @@@@ Page 1 of menu PROB
CLMENU
"COMB"
KEY 1 XEQ 41
"PERM"
KEY 2 XEQ 42
"GAMMA"
KEY 4 XEQ 43
"BETA"
KEY 5 XEQ 44
KEY 7 GTO 40
KEY 8 GTO 40
KEY 9 GTO 03
MENU
STOP
GTO 16
LBL 40            @@@@ Page 2 of menu PROB
CLMENU
"NPDF"
KEY 1 XEQ 45
"NCDF"
KEY 2 XEQ 46
KEY 7 GTO 16
KEY 8 GTO 16
KEY 9 GTO 03
MENU
STOP
GTO 40
LBL 17            @@@@ Page 1 of menu INT
CLMENU
"IDIV"
KEY 1 XEQ 47
"MOD"
KEY 2 XEQ 48
"GCD"
KEY 3 XEQ 49
"LCM"
KEY 4 XEQ 50
"FLOR"
KEY 5 XEQ 51
"CEIL"
KEY 6 XEQ 52
KEY 9 GTO 03
MENU
STOP
GTO 17
LBL 18            @@@@ Page 1 of menu CPLX
CLMENU
"RPART"
KEY 1 XEQ 53
"IPART"
KEY 2 XEQ 54
"CONJ"
KEY 3 XEQ 55
"CABS"
KEY 4 XEQ 56
"CARG"
KEY 5 XEQ 57
KEY 9 GTO 03
MENU
STOP
GTO 18
LBL 19            @@@@ Page 1 of menu TRIG
CLMENU
"HYPOT"
KEY 1 XEQ 58
"ATN2"
KEY 2 XEQ 59
KEY 9 GTO 12
MENU
STOP
GTO 19
LBL 20            @@@@ Page 1 of menu ERR
CLMENU
"ERF"
KEY 1 XEQ 60
"ERFC"
KEY 2 XEQ 61
"NPDF"
KEY 4 XEQ 62
"NCDF"
KEY 5 XEQ 63
KEY 9 GTO 12
MENU
STOP
GTO 20
LBL 04            @@@@ Page 1 of menu MATH
CLMENU
"POLY"
KEY 1 GTO 64
"FMENU"
KEY 2 XEQ 65
"3VEC"
KEY 3 XEQ 66
KEY 9 GTO 01
MENU
STOP
GTO 04
LBL 64            @@@@ Page 1 of menu POLY
CLMENU
"QEQ"
KEY 1 XEQ 67
"PLYE"
KEY 2 XEQ 68
KEY 9 GTO 04
MENU
STOP
GTO 64
LBL 05            @@@@ Page 1 of menu PHIL
CLMENU
"PERF"
KEY 1 XEQ 69
"IMET"
KEY 2 XEQ 70
"MEAS"
KEY 3 XEQ 71
KEY 9 GTO 01
MENU
STOP
GTO 05
LBL 11            @@@@ Page 1 of menu OPT
CLMENU
"SPREF"
KEY 1 XEQ 72
"MKCM"
KEY 2 XEQ 73
KEY 9 GTO 02
MENU
STOP
GTO 11
LBL 00 @@@@ Application Exit
EXITALL
RTN
LBL 06               @@@@ Action for menu key BASE
XEQ "BASE"
RTN
LBL 07               @@@@ Action for menu key DATE
XEQ "DMENU"
RTN
LBL 08               @@@@ Action for menu key CONS
XEQ "CONS"
RTN
LBL 09               @@@@ Action for menu key UNIT
XEQ "UNIT"
RTN
LBL 10               @@@@ Action for menu key MEAS
XEQ "MEAS"
RTN
LBL 21               @@@@ Action for menu key SINH
SINH
RTN
LBL 22               @@@@ Action for menu key COSH
COSH
RTN
LBL 23               @@@@ Action for menu key TANH
TANH
RTN
LBL 24               @@@@ Action for menu key ASINH
ASINH
RTN
LBL 25               @@@@ Action for menu key ACOSH
ACOSH
RTN
LBL 26               @@@@ Action for menu key ATANH
ATANH
RTN
LBL 28               @@@@ Action for menu key lnYX
XEQ "lnYX"
RTN
LBL 29               @@@@ Action for menu key Y√X
XEQ "YROOT"
RTN
LBL 30               @@@@ Action for menu key Y↑X
Y↑X
RTN
LBL 31               @@@@ Action for menu key ln2
XEQ "ln2"
RTN
LBL 32               @@@@ Action for menu key 2↑X
XEQ "2↑X"
RTN
LBL 33               @@@@ Action for menu key LN
LN
RTN
LBL 34               @@@@ Action for menu key EXP
XEQ "EXP"
RTN
LBL 35               @@@@ Action for menu key LOG
LOG
RTN
LBL 36               @@@@ Action for menu key 10↑X
10↑X
RTN
LBL 37               @@@@ Action for menu key %T
XEQ "%T"
RTN
LBL 38               @@@@ Action for menu key %CH
%CH
RTN
LBL 39               @@@@ Action for menu key %
%
RTN
LBL 41               @@@@ Action for menu key COMB
COMB
RTN
LBL 42               @@@@ Action for menu key PERM
PERM
RTN
LBL 43               @@@@ Action for menu key GAMMA
GAMMA
RTN
LBL 44               @@@@ Action for menu key BETA
XEQ "BETA"
RTN
LBL 45               @@@@ Action for menu key NPDF
XEQ "NPDF"
RTN
LBL 46               @@@@ Action for menu key NCDF
XEQ "NCDF"
RTN
LBL 47               @@@@ Action for menu key IDIV
BASE÷
RTN
LBL 48               @@@@ Action for menu key MOD
MOD
RTN
LBL 49               @@@@ Action for menu key GCD
XEQ "GCD"
RTN
LBL 50               @@@@ Action for menu key LCM
XEQ "LCM"
RTN
LBL 51               @@@@ Action for menu key FLOR
XEQ "FLOOR"
RTN
LBL 52               @@@@ Action for menu key CEIL
XEQ "CEIL"
RTN
LBL 53               @@@@ Action for menu key RPART
XEQ "RPART"
RTN
LBL 54               @@@@ Action for menu key IPART
XEQ "IPART"
RTN
LBL 55               @@@@ Action for menu key CONJ
XEQ "CONJ"
RTN
LBL 56               @@@@ Action for menu key CABS
XEQ "CABS"
RTN
LBL 57               @@@@ Action for menu key CARG
XEQ "CARG"
RTN
LBL 58               @@@@ Action for menu key HYPOT
XEQ "HYPOT"
RTN
LBL 59               @@@@ Action for menu key ATN2
XEQ "ATAN2"
RTN
LBL 60               @@@@ Action for menu key ERF
XEQ "ERF"
RTN
LBL 61               @@@@ Action for menu key ERFC
XEQ "ERFC"
RTN
LBL 62               @@@@ Action for menu key NPDF
XEQ "NPDF"
RTN
LBL 63               @@@@ Action for menu key NCDF
XEQ "NCDF"
RTN
LBL 65               @@@@ Action for menu key FMENU
XEQ "FMENU"
RTN
LBL 66               @@@@ Action for menu key 3VEC
XEQ "3VEC"
RTN
LBL 67               @@@@ Action for menu key QEQ
XEQ "QUADE"
RTN
LBL 68               @@@@ Action for menu key PLYE
XEQ "PLYE"
RTN
LBL 69               @@@@ Action for menu key PERF
XEQ "PERF"
RTN
LBL 70               @@@@ Action for menu key IMET
XEQ "IMET"
RTN
LBL 71               @@@@ Action for menu key MEAS
XEQ "MEAS"
RTN
LBL 72               @@@@ Action for menu key SPREF
XEQ "SPREF"
RTN
LBL 73               @@@@ Action for menu key MKCM
XEQ "MKCM"
RTN
@@@@ Free labels start at: 74
END
#+end_src

* Create system =CUSTOM= Menu
:PROPERTIES:
:CUSTOM_ID: system-custom
:END:

Sometimes our carefully built in =CUSTOM= menu is lost -- an errant program or system memory clear.  What to do?  How about a program that will recreate your
=CUSTOM= menu when you need it?  In the table below we have the definition of our custom menu, and a bit of lisp that will write a 42s program to =ASSIGN=
each key.

#+ATTR_HTML: :rules groups :frame box :align center
#+NAME: custom
| KEY# | ASSIGNment |
|------+------------|
|   01 | CUST       |
|   02 | VirtV      |
|   03 |            |
|   04 |            |
|   05 |            |
|   06 |            |
|------+------------|
|   07 |            |
|   08 |            |
|   09 |            |
|   10 |            |
|   11 |            |
|   12 |            |
|------+------------|
|   13 | SST        |
|   14 | SST↑       |
|   15 | SST→       |
|   16 | GTO        |
|   17 | VIEW       |
|   18 | AVIEW      |
|------+------------|

Simply evaluate the followign lisp block, and the 42s program will be created.

#+BEGIN_SRC elisp :var tbl=custom :colnames y :results output verbatum :wrap "src hp42s :tangle yes"
(princ (message "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ (ref:%s)\n" "MKCM"))
(princ "@@@@ DSC: Autogenerated menu program\n")
(princ "LBL \"MKCM\"\n")
(cl-loop for (da-key da-assignment da-note) in tbl
         ;;when (not (zerop (length da-assignment)))
         do (princ (message "ASSIGN \"%s\" TO %s\n" da-assignment da-key)))
(princ "RTN\n")
(princ "END\n")
#+END_SRC

#+RESULTS:
#+begin_src hp42s :tangle yes
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ (ref:MKCM)
@@@@ DSC: Autogenerated menu program
LBL "MKCM"
ASSIGN "CUST" TO 01
ASSIGN "VirtV" TO 02
ASSIGN "" TO 03
ASSIGN "" TO 04
ASSIGN "" TO 05
ASSIGN "" TO 06
ASSIGN "" TO 07
ASSIGN "" TO 08
ASSIGN "" TO 09
ASSIGN "" TO 10
ASSIGN "" TO 11
ASSIGN "" TO 12
ASSIGN "SST" TO 13
ASSIGN "SST↑" TO 14
ASSIGN "SST→" TO 15
ASSIGN "GTO" TO 16
ASSIGN "VIEW" TO 17
ASSIGN "AVIEW" TO 18
RTN
END
#+end_src

* =SPREF=: Set some of my personal prefrences

#+BEGIN_SRC hp42s :tangle yes
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ (ref:SPREF)
@@@@ DSC: Set some of my personal prefrences
@@@@ IN:  N/A
@@@@ OUT: N/A
@@@@ TST: free42_3.0.2
@@@@ BUG: This sets some of *my* favorite prefrences.  You might not like them. ;)
@@@@ UPD: 2021-04-05
LBL "SPREF"
FUNC 00
ALL     @@@@ Display all digits
RECT    @@@@ Complex number format
RAD     @@@@ Angle mode
CPXRES  @@@@ Complex results
RDX.    @@@@ Use periods
KEYASN  @@@@ Custom menu
DECM    @@@@ Make sure we are in decimal mode
64      @@@@ WSIZE
FS? 78
BSIGNED @@@@ Unsigned integer mode
FS? 79
BWRAP   @@@@ Don't wrap integers
DMY     @@@@ D.MY mode
CL12    @@@@ AM/PM mode
4STK    @@@@ Four level stack
EXITALL @@@@ Exit menus
RTN
END
#+END_SRC

* WORKING                                                          :noexport:

#+BEGIN_SRC text
:::::::::::::::::::::::'##:::::'##::::'###::::'########::'##::: ##:'####:'##::: ##::'######::::::::::::::::::::::::
::::::::::::::::::::::: ##:'##: ##:::'## ##::: ##.... ##: ###:: ##:. ##:: ###:: ##:'##... ##:::::::::::::::::::::::
::::::::::::::::::::::: ##: ##: ##::'##:. ##:: ##:::: ##: ####: ##:: ##:: ####: ##: ##:::..::::::::::::::::::::::::
::::::::::::::::::::::: ##: ##: ##:'##:::. ##: ########:: ## ## ##:: ##:: ## ## ##: ##::'####::::::::::::::::::::::
::::::::::::::::::::::: ##: ##: ##: #########: ##.. ##::: ##. ####:: ##:: ##. ####: ##::: ##:::::::::::::::::::::::
::::::::::::::::::::::: ##: ##: ##: ##.... ##: ##::. ##:: ##:. ###:: ##:: ##:. ###: ##::: ##:::::::::::::::::::::::
:::::::::::::::::::::::. ###. ###:: ##:::: ##: ##:::. ##: ##::. ##:'####: ##::. ##:. ######::::::::::::::::::::::::
::::::::::::::::::::::::...::...:::..:::::..::..:::::..::..::::..::....::..::::..:::......:::::::::::::::::::::::::
#+END_SRC

Code in this section is under construction.  Most likely broken.

* EOF

# End of document.

# The following adds some space at the bottom of exported HTML
#+HTML: <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br />
#+HTML: <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br />
#+HTML: <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br />
#+HTML: <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br />
#+HTML: <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br />
