# -*- Mode:Org; Coding:utf-8; fill-column:158 -*-
#+TITLE:       free42 Custom Unit Conversion Factors
#+AUTHOR:      Mitch Richling
#+EMAIL:       http://www.mitchr.me/
#+DATE:        2021-03-19
#+DESCRIPTION: Description of some free42/hp-42s/DM42 programs for unit computations
#+LANGUAGE:    en
#+OPTIONS:     num:t toc:nil \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:t skip:nil d:nil todo:t pri:nil H:5 p:t author:t html-scripts:nil
#+HTML_HEAD: <style>body { width: 95%; margin: 2% auto; font-size: 18px; line-height: 1.4em; font-family: Georgia, serif; color: black; background-color: white; }</style>
#+HTML_HEAD: <style>body { min-width: 500px; max-width: 1024px; }</style>
#+HTML_HEAD: <style>h1,h2,h3,h4,h5,h6 { color: #A5573E; line-height: 1em; font-family: Helvetica, sans-serif; }</style>
#+HTML_HEAD: <style>h1,h2,h3 { line-height: 1.4em; }</style>
#+HTML_HEAD: <style>h1.title { font-size: 3em; }</style>
#+HTML_HEAD: <style>h4,h5,h6 { font-size: 1em; }</style>
#+HTML_HEAD: <style>.org-src-container { border: 1px solid #ccc; box-shadow: 3px 3px 3px #eee; font-family: Lucida Console, monospace; font-size: 80%; margin: 0px; padding: 0px 0px; position: relative; }</style>
#+HTML_HEAD: <style>.org-src-container>pre { line-height: 1.2em; padding-top: 1.5em; margin: 0.5em; background-color: #404040; color: white; overflow: auto; }</style>
#+HTML_HEAD: <style>.org-src-container>pre:before { display: block; position: absolute; background-color: #b3b3b3; top: 0; right: 0; padding: 0 0.2em 0 0.4em; border-bottom-left-radius: 8px; border: 0; color: white; font-size: 100%; font-family: Helvetica, sans-serif;}</style>
#+HTML_HEAD: <style>pre.example { white-space: pre-wrap; white-space: -moz-pre-wrap; white-space: -o-pre-wrap; font-family: Lucida Console, monospace; font-size: 80%; background: #404040; color: white; display: block; padding: 0em; border: 2px solid black; }</style>
#+HTML_LINK_HOME: https://www.mitchr.me/
#+HTML_LINK_UP: https://richmit.github.io/hp42/
#+EXPORT_FILE_NAME: ../docs/unit

#+ATTR_HTML: :border 2 solid #ccc :frame hsides :align center
|        <r> | <l>              |
|  *Author:* | /{{{author}}}/ |
| *Updated:* | /{{{time(%Y-%m-%d %H:%M:%S)}}}/ |
#+ATTR_HTML: :align center
Copyright {{{time(%Y)}}} Mitch Richling. All rights reserved.

#+TOC: headlines 5

#        #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #
#   00   #    10   #    20   #    30   #    40   #    50   #    60   #    70   #    80   #    90   #   100   #   110   #   120   #   130   #   140   #   150   #   160   #
# 234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
#        #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #
#        #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #

* Metadata

The home for this HTML file is: https://richmit.github.io/hp42/unit.html

Files related to this document may be found on github: https://github.com/richmit/hp42

Directory contents:
#+ATTR_HTML: :border 0 :frame none :rules none :align center
   | =src=     | - | The org-mode file that generated this HTML document            |
   | =src_42s= | - | Ready to convert source listings for 42s code in this document |
   | =docs=    | - | This html document                                             |
   | =bin=     | - | Importable RAW program files                                   |

* Introduction
:PROPERTIES:
:CUSTOM_ID: introduction
:END:

This application has a few unit conversions for temperatures; however, the focus is on a nice way to organize and recall various conversion factors I
frequently use.  That is to say, I don't really want to convert "in" to "cm", instead I want to push the conversion factor to the stack.

Aside from the =TEMP= menu, all of the menus have the same structure.  The first menu key is the "base" unit for that page.  Pressing any menu key will push
a conversion factor for the given unit to the "base" unit to the stack.  For example, if the left most menu is "mm" then pressing the "in" button will push
25.4 to the stack -- the value you would multiply by to convert from inches to millimeters or divide by to convert from millimeters to inches.

* Units

** Conversion Factors

#+ATTR_HTML: :rules groups :frame box :align center
#+NAME: units
| Type        |       Conversion | Description     |
|-------------+------------------+-----------------|
| Leng:mm     |              1.0 |                 |
| Leng:Ang    |             1e-7 | Angstrom        |
| Leng:μm     |            0.001 | Micron          |
| Leng:mil    |           0.0254 | mil (1/1000 in) |
| Leng:cm     |               10 |                 |
| Leng:in     |             25.4 | Inch            |
|-------------+------------------+-----------------|
| Leng:cm     |                1 |                 |
| Leng:in     |             25.4 | Intl Inch       |
| Leng:ft     |            304.8 | Intl Foot       |
| Leng:m      |              100 |                 |
| Leng:yd     |            914.4 | Intl Yard       |
| Leng:▒▒▒▒   |                  |                 |
|-------------+------------------+-----------------|
| Leng:km     |                1 |                 |
| Leng:mi     |         1.609344 | Int Mile        |
| Leng:us mi  |    1.60934721869 | US Mile         |
| Leng:nmi    |            1.852 | Int Nautical mi |
| Leng:m      |            0.001 |                 |
| Leng:ft     |        0.0003048 | Intl Foot       |
|-------------+------------------+-----------------|
| Area:hector |                1 | hector          |
| Area:acre   |    0.40468564224 | Int Acre        |
| Area:m^2    |           0.0001 |                 |
| Area:yd^2   | 8.36127360001e-5 |                 |
|-------------+------------------+-----------------|
| Vol:l       |                1 |                 |
| Vol:qt      |   0.946352949997 | US Lq Quart     |
| Vol:gal     |        3.7854118 | US Lq Gal       |
| Vol:cc      |            0.001 |                 |
| Vol:▒▒▒▒    |                  |                 |
| Vol:▒▒▒▒    |                  |                 |
|-------------+------------------+-----------------|
| Vol:tsp     |                1 | Teaspoon        |
| Vol:tbsp    |                4 | Tablespoon      |
| Vol:flOZ    |                8 | fl oz           |
| Vol:cup     |               16 | Cup             |
| Vol:pint    |              128 | Pint            |
| Vol:qt      |              256 | Quart           |
|-------------+------------------+-----------------|
| Time:sec    |                1 |                 |
| Time:min    |               60 |                 |
| Time:hour   |             3600 |                 |
| Time:day    |            86400 |                 |
| Time:week   |           604800 |                 |
| Time:year   |         31536000 | 365 day year    |
|-------------+------------------+-----------------|
| Time:day    |                1 |                 |
| Time:year   |              365 |                 |
| Time:greg   |         365.2425 |                 |
| Time:julian |           365.25 |                 |
| Time:astro  |    365.256363004 |                 |
|-------------+------------------+-----------------|
| Mass:kg     |                1 |                 |
| Mass:lb     |  2.2046226218488 | Pound Int       |
| Mass:g      |              1e3 |                 |
| Mass:ozWT   |   35.27396194958 | Ounce Weight    |
| Mass:ozTr   |  32.150746568628 | Ounce Troy      |
| Mass:stone  | 0.15747304441777 | UK Stone        |
|-------------+------------------+-----------------|
| Mass:kg     |                1 |                 |
| Mass:ton    |            0.001 | Metric Ton      |
| Mass:US ton |    907.184736885 | US (short) Ton  |
| Mass:UK ton |    1016.04690531 | UK (long) Ton   |
|-------------+------------------+-----------------|
| Force:N     |                1 |                 |
| Force:kgf   |          9.80665 |                 |
| Force:lbf   |     4.4482216153 | Int Pound Force |
|-------------+------------------+-----------------|
| Sped:m/s    |                1 |                 |
| Sped:mph    |          0.44704 | Int Mi per hour |
| Sped:kph    |     0.2777777778 |                 |
| Sped:knot   |     0.5144444444 | International   |
|-------------+------------------+-----------------|
| Pres:Pa     |                1 | N/m^2           |
| Pres:bar    |           100000 |                 |
| Pres:psi    |     6894.7572932 |                 |
| Pres:atm    |           101325 |                 |
| Pres:mmHg   |          133.322 |                 |
| Pres:inHg   |         3386.389 |                 |
|-------------+------------------+-----------------|
| Powr:watt   |                1 |                 |
| Powr:BTU/h  |     0.2930710702 | International   |
| Powr:hp     |        735.49875 | Metric          |
| Powr:kcal/h |            1.163 |                 |
| Powr:J/h    |     0.0002777778 |                 |
|-------------+------------------+-----------------|
| Temp:C→F    |     9 × 5 ÷ 32 + |                 |
| Temp:F→C    |     32 - 5 × 9 ÷ |                 |
| Temp:K→C    |         273.15 - |                 |
| Temp:C→K    |         273.15 + |                 |
|-------------+------------------+-----------------|

** Code

#+BEGIN_SRC elisp :var tbl=units :colnames y :results output verbatum :wrap "src hp42s :tangle ../src_42s/unit/unit.hp42s"
(MJR-generate-42-menu-code "UNIT" 
                           tbl
                           "stay"
                           "up" 
                           nil
                           (lambda (row) 
                             (cl-destructuring-bind (menu cfactor desc) row
                               (let ((print-desc 't))    ;; Set to NIL to not print description
                                 (let* ((dlen (length desc))
                                        (dsc1 (if (> dlen 0)
                                                  (substring desc 0 (min dlen 15))))
                                        (dsc2 (if (> dlen 14)
                                                  (substring desc 15 (min dlen 22)))))
                                   (mapconcat #'identity
                                              (cl-remove nil (flatten-list
                                                              (list (split-string (message "%s" cfactor))
                                                                    (and print-desc dsc1 (message "\"%s\"" dsc1))
                                                                    (and print-desc dsc2 (message "├\"%s\"" dsc2))
                                                                    (and print-desc (or dsc1 dsc2) "AVIEW"))))
                                              "\n")))))))
#+END_SRC

#+RESULTS:
#+begin_src hp42s :tangle ../src_42s/unit/unit.hp42s
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ (ref:UNIT)
@@@@ DSC: Auto-generated menu program
LBL "UNIT"
LBL 01            @@@@ Page 1 of menu UNIT
CLMENU
"Leng"
KEY 1 GTO 03
"Area"
KEY 2 GTO 04
"Vol"
KEY 3 GTO 05
"Time"
KEY 4 GTO 06
"Mass"
KEY 5 GTO 07
"Force"
KEY 6 GTO 08
KEY 7 GTO 02
KEY 8 GTO 02
KEY 9 GTO 00
MENU
STOP
GTO 01
LBL 02            @@@@ Page 2 of menu UNIT
CLMENU
"Sped"
KEY 1 GTO 09
"Pres"
KEY 2 GTO 10
"Powr"
KEY 3 GTO 11
"Temp"
KEY 4 GTO 12
KEY 7 GTO 01
KEY 8 GTO 01
KEY 9 GTO 00
MENU
STOP
GTO 02
LBL 03            @@@@ Page 1 of menu Leng
CLMENU
"mm"
KEY 1 XEQ 15
"Ang"
KEY 2 XEQ 16
"μm"
KEY 3 XEQ 17
"mil"
KEY 4 XEQ 18
"cm"
KEY 5 XEQ 19
"in"
KEY 6 XEQ 20
KEY 7 GTO 14
KEY 8 GTO 13
KEY 9 GTO 01
MENU
STOP
GTO 03
LBL 13            @@@@ Page 2 of menu Leng
CLMENU
"cm"
KEY 1 XEQ 21
"in"
KEY 2 XEQ 22
"ft"
KEY 3 XEQ 23
"m"
KEY 4 XEQ 24
"yd"
KEY 5 XEQ 25
KEY 7 GTO 03
KEY 8 GTO 14
KEY 9 GTO 01
MENU
STOP
GTO 13
LBL 14            @@@@ Page 3 of menu Leng
CLMENU
"km"
KEY 1 XEQ 26
"mi"
KEY 2 XEQ 27
"us mi"
KEY 3 XEQ 28
"nmi"
KEY 4 XEQ 29
"m"
KEY 5 XEQ 30
"ft"
KEY 6 XEQ 31
KEY 7 GTO 13
KEY 8 GTO 03
KEY 9 GTO 01
MENU
STOP
GTO 14
LBL 04            @@@@ Page 1 of menu Area
CLMENU
"hector"
KEY 1 XEQ 32
"acre"
KEY 2 XEQ 33
"m^2"
KEY 3 XEQ 34
"yd^2"
KEY 4 XEQ 35
KEY 9 GTO 01
MENU
STOP
GTO 04
LBL 05            @@@@ Page 1 of menu Vol
CLMENU
"l"
KEY 1 XEQ 37
"qt"
KEY 2 XEQ 38
"gal"
KEY 3 XEQ 39
"cc"
KEY 4 XEQ 40
KEY 7 GTO 36
KEY 8 GTO 36
KEY 9 GTO 01
MENU
STOP
GTO 05
LBL 36            @@@@ Page 2 of menu Vol
CLMENU
"tsp"
KEY 1 XEQ 41
"tbsp"
KEY 2 XEQ 42
"flOZ"
KEY 3 XEQ 43
"cup"
KEY 4 XEQ 44
"pint"
KEY 5 XEQ 45
"qt"
KEY 6 XEQ 46
KEY 7 GTO 05
KEY 8 GTO 05
KEY 9 GTO 01
MENU
STOP
GTO 36
LBL 06            @@@@ Page 1 of menu Time
CLMENU
"sec"
KEY 1 XEQ 48
"min"
KEY 2 XEQ 49
"hour"
KEY 3 XEQ 50
"day"
KEY 4 XEQ 51
"week"
KEY 5 XEQ 52
"year"
KEY 6 XEQ 53
KEY 7 GTO 47
KEY 8 GTO 47
KEY 9 GTO 01
MENU
STOP
GTO 06
LBL 47            @@@@ Page 2 of menu Time
CLMENU
"day"
KEY 1 XEQ 54
"year"
KEY 2 XEQ 55
"greg"
KEY 3 XEQ 56
"julian"
KEY 4 XEQ 57
"astro"
KEY 5 XEQ 58
KEY 7 GTO 06
KEY 8 GTO 06
KEY 9 GTO 01
MENU
STOP
GTO 47
LBL 07            @@@@ Page 1 of menu Mass
CLMENU
"kg"
KEY 1 XEQ 60
"lb"
KEY 2 XEQ 61
"g"
KEY 3 XEQ 62
"ozWT"
KEY 4 XEQ 63
"ozTr"
KEY 5 XEQ 64
"stone"
KEY 6 XEQ 65
KEY 7 GTO 59
KEY 8 GTO 59
KEY 9 GTO 01
MENU
STOP
GTO 07
LBL 59            @@@@ Page 2 of menu Mass
CLMENU
"kg"
KEY 1 XEQ 66
"ton"
KEY 2 XEQ 67
"US ton"
KEY 3 XEQ 68
"UK ton"
KEY 4 XEQ 69
KEY 7 GTO 07
KEY 8 GTO 07
KEY 9 GTO 01
MENU
STOP
GTO 59
LBL 08            @@@@ Page 1 of menu Force
CLMENU
"N"
KEY 1 XEQ 70
"kgf"
KEY 2 XEQ 71
"lbf"
KEY 3 XEQ 72
KEY 9 GTO 01
MENU
STOP
GTO 08
LBL 09            @@@@ Page 1 of menu Sped
CLMENU
"m/s"
KEY 1 XEQ 73
"mph"
KEY 2 XEQ 74
"kph"
KEY 3 XEQ 75
"knot"
KEY 4 XEQ 76
KEY 9 GTO 02
MENU
STOP
GTO 09
LBL 10            @@@@ Page 1 of menu Pres
CLMENU
"Pa"
KEY 1 XEQ 77
"bar"
KEY 2 XEQ 78
"psi"
KEY 3 XEQ 79
"atm"
KEY 4 XEQ 80
"mmHg"
KEY 5 XEQ 81
"inHg"
KEY 6 XEQ 82
KEY 9 GTO 02
MENU
STOP
GTO 10
LBL 11            @@@@ Page 1 of menu Powr
CLMENU
"watt"
KEY 1 XEQ 83
"BTU/h"
KEY 2 XEQ 84
"hp"
KEY 3 XEQ 85
"kcal/h"
KEY 4 XEQ 86
"J/h"
KEY 5 XEQ 87
KEY 9 GTO 02
MENU
STOP
GTO 11
LBL 12            @@@@ Page 1 of menu Temp
CLMENU
"C→F"
KEY 1 XEQ 88
"F→C"
KEY 2 XEQ 89
"K→C"
KEY 3 XEQ 90
"C→K"
KEY 4 XEQ 91
KEY 9 GTO 02
MENU
STOP
GTO 12
LBL 00 @@@@ Application Exit
EXITALL
RTN
LBL 15               @@@@ Action for menu key mm
1.0
RTN
LBL 16               @@@@ Action for menu key Ang
1e-07
"Angstrom"
AVIEW
RTN
LBL 17               @@@@ Action for menu key μm
0.001
"Micron"
AVIEW
RTN
LBL 18               @@@@ Action for menu key mil
0.0254
"mil (1/1000 in)"
├""
AVIEW
RTN
LBL 19               @@@@ Action for menu key cm
10
RTN
LBL 20               @@@@ Action for menu key in
25.4
"Inch"
AVIEW
RTN
LBL 21               @@@@ Action for menu key cm
1
RTN
LBL 22               @@@@ Action for menu key in
25.4
"Intl Inch"
AVIEW
RTN
LBL 23               @@@@ Action for menu key ft
304.8
"Intl Foot"
AVIEW
RTN
LBL 24               @@@@ Action for menu key m
100
RTN
LBL 25               @@@@ Action for menu key yd
914.4
"Intl Yard"
AVIEW
RTN
LBL 26               @@@@ Action for menu key km
1
RTN
LBL 27               @@@@ Action for menu key mi
1.609344
"Int Mile"
AVIEW
RTN
LBL 28               @@@@ Action for menu key us mi
1.60934721869
"US Mile"
AVIEW
RTN
LBL 29               @@@@ Action for menu key nmi
1.852
"Int Nautical mi"
├""
AVIEW
RTN
LBL 30               @@@@ Action for menu key m
0.001
RTN
LBL 31               @@@@ Action for menu key ft
0.0003048
"Intl Foot"
AVIEW
RTN
LBL 32               @@@@ Action for menu key hector
1
"hector"
AVIEW
RTN
LBL 33               @@@@ Action for menu key acre
0.40468564224
"Int Acre"
AVIEW
RTN
LBL 34               @@@@ Action for menu key m^2
0.0001
RTN
LBL 35               @@@@ Action for menu key yd^2
8.36127360001e-05
RTN
LBL 37               @@@@ Action for menu key l
1
RTN
LBL 38               @@@@ Action for menu key qt
0.946352949997
"US Lq Quart"
AVIEW
RTN
LBL 39               @@@@ Action for menu key gal
3.7854118
"US Lq Gal"
AVIEW
RTN
LBL 40               @@@@ Action for menu key cc
0.001
RTN
LBL 41               @@@@ Action for menu key tsp
1
"Teaspoon"
AVIEW
RTN
LBL 42               @@@@ Action for menu key tbsp
4
"Tablespoon"
AVIEW
RTN
LBL 43               @@@@ Action for menu key flOZ
8
"fl oz"
AVIEW
RTN
LBL 44               @@@@ Action for menu key cup
16
"Cup"
AVIEW
RTN
LBL 45               @@@@ Action for menu key pint
128
"Pint"
AVIEW
RTN
LBL 46               @@@@ Action for menu key qt
256
"Quart"
AVIEW
RTN
LBL 48               @@@@ Action for menu key sec
1
RTN
LBL 49               @@@@ Action for menu key min
60
RTN
LBL 50               @@@@ Action for menu key hour
3600
RTN
LBL 51               @@@@ Action for menu key day
86400
RTN
LBL 52               @@@@ Action for menu key week
604800
RTN
LBL 53               @@@@ Action for menu key year
31536000
"365 day year"
AVIEW
RTN
LBL 54               @@@@ Action for menu key day
1
RTN
LBL 55               @@@@ Action for menu key year
365
RTN
LBL 56               @@@@ Action for menu key greg
365.2425
RTN
LBL 57               @@@@ Action for menu key julian
365.25
RTN
LBL 58               @@@@ Action for menu key astro
365.256363004
RTN
LBL 60               @@@@ Action for menu key kg
1
RTN
LBL 61               @@@@ Action for menu key lb
2.2046226218488
"Pound Int"
AVIEW
RTN
LBL 62               @@@@ Action for menu key g
1000.0
RTN
LBL 63               @@@@ Action for menu key ozWT
35.27396194958
"Ounce Weight"
AVIEW
RTN
LBL 64               @@@@ Action for menu key ozTr
32.150746568628
"Ounce Troy"
AVIEW
RTN
LBL 65               @@@@ Action for menu key stone
0.15747304441777
"UK Stone"
AVIEW
RTN
LBL 66               @@@@ Action for menu key kg
1
RTN
LBL 67               @@@@ Action for menu key ton
0.001
"Metric Ton"
AVIEW
RTN
LBL 68               @@@@ Action for menu key US ton
907.184736885
"US (short) Ton"
AVIEW
RTN
LBL 69               @@@@ Action for menu key UK ton
1016.04690531
"UK (long) Ton"
AVIEW
RTN
LBL 70               @@@@ Action for menu key N
1
RTN
LBL 71               @@@@ Action for menu key kgf
9.80665
RTN
LBL 72               @@@@ Action for menu key lbf
4.4482216153
"Int Pound Force"
├""
AVIEW
RTN
LBL 73               @@@@ Action for menu key m/s
1
RTN
LBL 74               @@@@ Action for menu key mph
0.44704
"Int Mi per hour"
├""
AVIEW
RTN
LBL 75               @@@@ Action for menu key kph
0.2777777778
RTN
LBL 76               @@@@ Action for menu key knot
0.5144444444
"International"
AVIEW
RTN
LBL 77               @@@@ Action for menu key Pa
1
"N/m^2"
AVIEW
RTN
LBL 78               @@@@ Action for menu key bar
100000
RTN
LBL 79               @@@@ Action for menu key psi
6894.7572932
RTN
LBL 80               @@@@ Action for menu key atm
101325
RTN
LBL 81               @@@@ Action for menu key mmHg
133.322
RTN
LBL 82               @@@@ Action for menu key inHg
3386.389
RTN
LBL 83               @@@@ Action for menu key watt
1
RTN
LBL 84               @@@@ Action for menu key BTU/h
0.2930710702
"International"
AVIEW
RTN
LBL 85               @@@@ Action for menu key hp
735.49875
"Metric"
AVIEW
RTN
LBL 86               @@@@ Action for menu key kcal/h
1.163
RTN
LBL 87               @@@@ Action for menu key J/h
0.0002777778
RTN
LBL 88               @@@@ Action for menu key C→F
9
×
5
÷
32
+
RTN
LBL 89               @@@@ Action for menu key F→C
32
-
5
×
9
÷
RTN
LBL 90               @@@@ Action for menu key K→C
273.15
-
RTN
LBL 91               @@@@ Action for menu key C→K
273.15
+
RTN
@@@@ Free labels start at: 92
END
#+end_src

* WORKING                                                          :noexport:

#+BEGIN_SRC text
:::::::::::::::::::::::'##:::::'##::::'###::::'########::'##::: ##:'####:'##::: ##::'######::::::::::::::::::::::::
::::::::::::::::::::::: ##:'##: ##:::'## ##::: ##.... ##: ###:: ##:. ##:: ###:: ##:'##... ##:::::::::::::::::::::::
::::::::::::::::::::::: ##: ##: ##::'##:. ##:: ##:::: ##: ####: ##:: ##:: ####: ##: ##:::..::::::::::::::::::::::::
::::::::::::::::::::::: ##: ##: ##:'##:::. ##: ########:: ## ## ##:: ##:: ## ## ##: ##::'####::::::::::::::::::::::
::::::::::::::::::::::: ##: ##: ##: #########: ##.. ##::: ##. ####:: ##:: ##. ####: ##::: ##:::::::::::::::::::::::
::::::::::::::::::::::: ##: ##: ##: ##.... ##: ##::. ##:: ##:. ###:: ##:: ##:. ###: ##::: ##:::::::::::::::::::::::
:::::::::::::::::::::::. ###. ###:: ##:::: ##: ##:::. ##: ##::. ##:'####: ##::. ##:. ######::::::::::::::::::::::::
::::::::::::::::::::::::...::...:::..:::::..::..:::::..::..::::..::....::..::::..:::......:::::::::::::::::::::::::
#+END_SRC

Code in this section is under construction.  Most likely broken.
* EOF

# End of document.

# The following adds some space at the bottom of exported HTML
#+HTML: <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br />
#+HTML: <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br />
#+HTML: <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br />
#+HTML: <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br />
#+HTML: <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br /> <br />
