# -*- Mode:Org; Coding:utf-8; fill-column:158 -*-
#+TITLE:       free42/hp42s/DM42 Custom Unit Conversion Factors
#+AUTHOR:      Mitch Richling
#+EMAIL:       http://www.mitchr.me/
#+DATE:        2021-03-19
#+DESCRIPTION: Description of some free42/hp-42s/DM42 programs for unit computations
#+LANGUAGE:    en
#+OPTIONS:     num:t toc:nil \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:t skip:nil d:nil todo:t pri:nil H:5 p:t author:t html-scripts:nil 
#+HTML_HEAD: <style>body { width: 95%; margin: 2% auto; font-size: 18px; line-height: 1.4em; font-family: Georgia, serif; color: black; background-color: white; }</style>
#+HTML_HEAD: <style>body { min-width: 500px; max-width: 1024px; }</style>
#+HTML_HEAD: <style>h1,h2,h3,h4,h5,h6 { color: #A5573E; line-height: 1em; font-family: Helvetica, sans-serif; }</style>
#+HTML_HEAD: <style>h1,h2,h3 { line-height: 1.4em; }</style>
#+HTML_HEAD: <style>h1.title { font-size: 3em; }</style>
#+HTML_HEAD: <style>h4,h5,h6 { font-size: 1em; }</style>
#+HTML_HEAD: <style>.org-src-container { border: 1px solid #ccc; box-shadow: 3px 3px 3px #eee; font-family: Lucida Console, monospace; font-size: 80%; margin: 0px; padding: 0px 0px; position: relative; }</style>
#+HTML_HEAD: <style>.org-src-container>pre { line-height: 1.2em; padding-top: 1.5em; margin: 0.5em; background-color: #404040; color: white; overflow: auto; }</style>
#+HTML_HEAD: <style>.org-src-container>pre:before { display: block; position: absolute; background-color: #b3b3b3; top: 0; right: 0; padding: 0 0.2em 0 0.4em; border-bottom-left-radius: 8px; border: 0; color: white; font-size: 100%; font-family: Helvetica, sans-serif;}</style>
#+HTML_HEAD: <style>pre.example { white-space: pre-wrap; white-space: -moz-pre-wrap; white-space: -o-pre-wrap; font-family: Lucida Console, monospace; font-size: 80%; background: #404040; color: white; display: block; padding: 0em; border: 2px solid black; }</style>
#+HTML_LINK_HOME: https://www.mitchr.me/
#+HTML_LINK_UP: https://richmit.github.io/hp42/

#+ATTR_HTML: :border 2 solid #ccc :frame hsides :align center
|        <r> | <l>              |
|  *Author:* | /{{{author}}}/ |
| *Updated:* | /{{{time(%Y-%m-%d %H:%M:%S)}}}/ |
#+ATTR_HTML: :align center
Copyright {{{time(%Y)}}} Mitch Richling. All rights reserved.

#+TOC: headlines 5

#        #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #
#   00   #    10   #    20   #    30   #    40   #    50   #    60   #    70   #    80   #    90   #   100   #   110   #   120   #   130   #   140   #   150   #   160   #
# 234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
#        #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #
#        #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #         #

* Metadata

This home for this HTML file is: https://richmit.github.io/hp42/unit.html

Files related to this document may be found on github: https://github.com/richmit/hp42

   - =src= directory: Contains the org-mode file that generated this HTML document
   - =docs= directory: Contains this html document
   - =bin= directory: Contains raw program files

* Introduction

This application has a few unit conversions for temperatures; however, the focus is on a nice way to organize and recall various conversion factors I
frequently use.  That is to say, I don't really want to convert "in" to "cm", instead I want to push the conversion factor to the stack.

Aside from the =TEMP= menu, all of the menus have the same structure.  The first menu key is the "base" unit for that page.  Pressing any menu key will push
a conversion factor for the given unit to the "base" unit to the stack.  For example, if the left most menu is "mm" then pressing the "in" button will push
0.393700787402 to the stack -- the value you would multiply by to convert from inches to millimeters or divide by to convert from millimeters to inches.

* Units

** Conversion Factors

#+ATTR_HTML: :rules groups :frame box :align center
#+NAME: units
| Type        |         Conversion | Description     |
|-------------+--------------------+-----------------|
| LEN:mm      |                1.0 |                 |
| LEN:Ang     |                1e7 | Angstrom        |
| LEN:μm      |                1e3 | Micron          |
| LEN:mil     |  3.9370078740157e1 | mil (1/1000 in) |
| LEN:cm      |               1e-2 |                 |
| LEN:in      | 3.9370078740157e-2 | Inch            |
|-------------+--------------------+-----------------|
| LEN:cm      |                  1 |                 |
| LEN:in      |   0.39370078740157 | Intl Inch       |
| LEN:ft      |             0.3048 | Intl Foot       |
| LEN:m       |               1e-3 |                 |
| LEN:yd      |  0.032808398950131 | Intl Yard       |
|-------------+--------------------+-----------------|
| LEN:km      |                  1 |                 |
| LEN:mi      |   0.62137119223733 | Int Mile        |
| LEN:us mi   |   0.62136994949495 | US Mile         |
| LEN:nmi     |   0.53995680345572 | Int Nautical mi |
| LEN:m       |                1e3 |                 |
| LEN:ft      |    3280.8398950131 | Intl Foot       |
|-------------+--------------------+-----------------|
| AREA:hector |                  1 | hector          |
| AREA:acre   |    2.4710538146717 | Int Acre        |
| AREA:m^2    |              10000 |                 |
| AREA:yd^2   |    11959.900463011 |                 |
|-------------+--------------------+-----------------|
| VOL:l       |                  1 |                 |
| VOL:qt      |    1.0566882049662 | US Lq Quart     |
| VOL:gal     |   0.26417205124156 | US Lq Gal       |
| VOL:cc      |                1e3 |                 |
|-------------+--------------------+-----------------|
| VOL:gal     |                  1 | Gal             |
| VOL:qt      |                  4 | Quart           |
| VOL:pint    |                  8 | Pint            |
| VOL:cup     |                 16 | Cup             |
| VOL:flOZ    |                128 | fl oz           |
| VOL:tbsp    |                256 | Tablespoon      |
| VOL:tsp     |                768 | Teaspoon        |
|-------------+--------------------+-----------------|
| TIME:sec    |                  1 |                 |
| TIME:min    |                 60 |                 |
| TIME:hour   |               3600 |                 |
| TIME:day    |              86400 |                 |
| TIME:week   |             604800 |                 |
| TIME:year   |           31536000 | 365 day year    |
|-------------+--------------------+-----------------|
| TIME:day    |                  1 |                 |
| TIME:year   |                365 |                 |
| TIME:greg   |           365.2425 |                 |
| TIME:julian |             365.25 |                 |
| TIME:astro  |      365.256363004 |                 |
|-------------+--------------------+-----------------|
| Mass:kg     |                  1 |                 |
| Mass:lb     |    2.2046226218488 | Pound Int       |
| Mass:g      |                1e3 |                 |
| Mass:ozWT   |     35.27396194958 | Ounce Weight    |
| Mass:ozTr   |    32.150746568628 | Ounce Troy      |
| Mass:stone  |   0.15747304441777 | UK Stone        |
|-------------+--------------------+-----------------|
| Mass:kg     |                  1 |                 |
| Mass:ton    |              0.001 | Metric Ton      |
| Mass:US ton |   1.10231131471e-3 | US (short) Ton  |
| Mass:UK ton |   9.84206530988e-4 | UK (long) Ton   |
|-------------+--------------------+-----------------|
| Force:N     |                  1 |                 |
| Force:kgf   |            9.80665 |                 |
| Force:lbf   |       4.4482216153 | Int Pound Force |
|-------------+--------------------+-----------------|
| Sped:m/s    |                  1 |                 |
| Sped:mph    |            0.44704 | Int Mi per hour |
| Sped:kph    |       0.2777777778 |                 |
| Sped:knot   |       0.5144444444 | International   |
|-------------+--------------------+-----------------|
| PRES:Pa     |                  1 | N/m^2           |
| PRES:bar    |             100000 |                 |
| PRES:psi    |       6894.7572932 |                 |
| PRES:atm    |             101325 |                 |
| PRES:mmHg   |            133.322 |                 |
| PRES:inHg   |            133.322 |                 |
|-------------+--------------------+-----------------|
| POW:watt    |                  1 |                 |
| POW:BTU/h   |       0.2930710702 | International   |
| POW:hp      |          735.49875 | Metric          |
| POW:kcal/h  |              1.163 |                 |
| POW:J/h     |       0.0002777778 |                 |
|-------------+--------------------+-----------------|
| TEMP:C→F    |       9 × 5 ÷ 32 + |                 |
| TEMP:F→C    |       32 - 5 × 9 ÷ |                 |
| TEMP:K→C    |           273.15 - |                 |
| TEMP:C→K    |           273.15 + |                 |
|-------------+--------------------+-----------------|

** Code

#+BEGIN_SRC elisp :var tbl=units :colnames y :results output verbatum
  (MJR-generate-42-menu-code "UNIT" tbl "stay" "up" (lambda (row) (cl-destructuring-bind (menu cfactor desc) row
                                                                    (let ((print-desc 't))    ;; Set to NIL to not print description
                                                                      (let* ((dlen (length desc))
                                                                             (dsc1 (if (> dlen 0)
                                                                                    (substring desc 0 (min dlen 15))))
                                                                             (dsc2 (if (> dlen 14)
                                                                                       (substring desc 15 (min dlen 22)))))
                                                                        (mapconcat #'identity
                                                                                   (cl-remove nil (flatten-list (list (split-string (message "%s" cfactor))
                                                                                                                      (and print-desc dsc1 (message "\"%s\"" dsc1))
                                                                                                                      (and print-desc dsc2 (message "├\"%s\"" dsc2))
                                                                                                                      (and print-desc (or dsc1 dsc2) "AVIEW"))))
                                                                                   "\n")))))))
#+END_SRC

#+begin_src hp42s
LBL "UNIT"
LBL 01            @@@@ Page 1 of menu CONV
CLMENU
"LEN"
KEY 1 GTO 03
"AREA"
KEY 2 GTO 04
"VOL"
KEY 3 GTO 05
"TIME"
KEY 4 GTO 06
"Mass"
KEY 5 GTO 07
"Force"
KEY 6 GTO 08
KEY 7 GTO 02
KEY 8 GTO 02
KEY 9 GTO 00
MENU
STOP
GTO 01
LBL 02            @@@@ Page 2 of menu CONV
CLMENU
"Sped"
KEY 1 GTO 09
"PRES"
KEY 2 GTO 10
"POW"
KEY 3 GTO 11
"TEMP"
KEY 4 GTO 12
KEY 7 GTO 01
KEY 8 GTO 01
KEY 9 GTO 00
MENU
STOP
GTO 02
LBL 03            @@@@ Page 1 of menu LEN
CLMENU
"mm"
KEY 1 XEQ 15
"Ang"
KEY 2 XEQ 16
"μm"
KEY 3 XEQ 17
"mil"
KEY 4 XEQ 18
"cm"
KEY 5 XEQ 19
"in"
KEY 6 XEQ 20
KEY 7 GTO 14
KEY 8 GTO 13
KEY 9 GTO 01
MENU
STOP
GTO 03
LBL 13            @@@@ Page 2 of menu LEN
CLMENU
"cm"
KEY 1 XEQ 21
"in"
KEY 2 XEQ 22
"ft"
KEY 3 XEQ 23
"m"
KEY 4 XEQ 24
"yd"
KEY 5 XEQ 25
"km"
KEY 6 XEQ 26
KEY 7 GTO 03
KEY 8 GTO 14
KEY 9 GTO 01
MENU
STOP
GTO 13
LBL 14            @@@@ Page 3 of menu LEN
CLMENU
"mi"
KEY 1 XEQ 27
"us mi"
KEY 2 XEQ 28
"nmi"
KEY 3 XEQ 29
"m"
KEY 4 XEQ 30
"ft"
KEY 5 XEQ 31
KEY 7 GTO 13
KEY 8 GTO 03
KEY 9 GTO 01
MENU
STOP
GTO 14
LBL 04            @@@@ Page 1 of menu AREA
CLMENU
"hector"
KEY 1 XEQ 32
"acre"
KEY 2 XEQ 33
"m^2"
KEY 3 XEQ 34
"yd^2"
KEY 4 XEQ 35
KEY 9 GTO 01
MENU
STOP
GTO 04
LBL 05            @@@@ Page 1 of menu VOL
CLMENU
"l"
KEY 1 XEQ 37
"qt"
KEY 2 XEQ 38
"gal"
KEY 3 XEQ 39
"cc"
KEY 4 XEQ 40
"gal"
KEY 5 XEQ 41
"qt"
KEY 6 XEQ 42
KEY 7 GTO 36
KEY 8 GTO 36
KEY 9 GTO 01
MENU
STOP
GTO 05
LBL 36            @@@@ Page 2 of menu VOL
CLMENU
"pint"
KEY 1 XEQ 43
"cup"
KEY 2 XEQ 44
"flOZ"
KEY 3 XEQ 45
"tbsp"
KEY 4 XEQ 46
"tsp"
KEY 5 XEQ 47
KEY 7 GTO 05
KEY 8 GTO 05
KEY 9 GTO 01
MENU
STOP
GTO 36
LBL 06            @@@@ Page 1 of menu TIME
CLMENU
"sec"
KEY 1 XEQ 49
"min"
KEY 2 XEQ 50
"hour"
KEY 3 XEQ 51
"day"
KEY 4 XEQ 52
"week"
KEY 5 XEQ 53
"year"
KEY 6 XEQ 54
KEY 7 GTO 48
KEY 8 GTO 48
KEY 9 GTO 01
MENU
STOP
GTO 06
LBL 48            @@@@ Page 2 of menu TIME
CLMENU
"day"
KEY 1 XEQ 55
"year"
KEY 2 XEQ 56
"greg"
KEY 3 XEQ 57
"julian"
KEY 4 XEQ 58
"astro"
KEY 5 XEQ 59
KEY 7 GTO 06
KEY 8 GTO 06
KEY 9 GTO 01
MENU
STOP
GTO 48
LBL 07            @@@@ Page 1 of menu Mass
CLMENU
"kg"
KEY 1 XEQ 61
"lb"
KEY 2 XEQ 62
"g"
KEY 3 XEQ 63
"ozWT"
KEY 4 XEQ 64
"ozTr"
KEY 5 XEQ 65
"stone"
KEY 6 XEQ 66
KEY 7 GTO 60
KEY 8 GTO 60
KEY 9 GTO 01
MENU
STOP
GTO 07
LBL 60            @@@@ Page 2 of menu Mass
CLMENU
"kg"
KEY 1 XEQ 67
"ton"
KEY 2 XEQ 68
"US ton"
KEY 3 XEQ 69
"UK ton"
KEY 4 XEQ 70
KEY 7 GTO 07
KEY 8 GTO 07
KEY 9 GTO 01
MENU
STOP
GTO 60
LBL 08            @@@@ Page 1 of menu Force
CLMENU
"N"
KEY 1 XEQ 71
"kgf"
KEY 2 XEQ 72
"lbf"
KEY 3 XEQ 73
KEY 9 GTO 01
MENU
STOP
GTO 08
LBL 09            @@@@ Page 1 of menu Sped
CLMENU
"m/s"
KEY 1 XEQ 74
"mph"
KEY 2 XEQ 75
"kph"
KEY 3 XEQ 76
"knot"
KEY 4 XEQ 77
KEY 9 GTO 02
MENU
STOP
GTO 09
LBL 10            @@@@ Page 1 of menu PRES
CLMENU
"Pa"
KEY 1 XEQ 78
"bar"
KEY 2 XEQ 79
"psi"
KEY 3 XEQ 80
"atm"
KEY 4 XEQ 81
"mmHg"
KEY 5 XEQ 82
"inHg"
KEY 6 XEQ 83
KEY 9 GTO 02
MENU
STOP
GTO 10
LBL 11            @@@@ Page 1 of menu POW
CLMENU
"watt"
KEY 1 XEQ 84
"BTU/h"
KEY 2 XEQ 85
"hp"
KEY 3 XEQ 86
"kcal/h"
KEY 4 XEQ 87
"J/h"
KEY 5 XEQ 88
KEY 9 GTO 02
MENU
STOP
GTO 11
LBL 12            @@@@ Page 1 of menu TEMP
CLMENU
"C→F"
KEY 1 XEQ 89
"F→C"
KEY 2 XEQ 90
"K→C"
KEY 3 XEQ 91
"C→K"
KEY 4 XEQ 92
KEY 9 GTO 02
MENU
STOP
GTO 12
LBL 00
EXITALL
RTN
LBL 15               @@@@ Action for menu key mm
1.0
RTN
LBL 16               @@@@ Action for menu key Ang
1e7
"Angstrom"
AVIEW
RTN
LBL 17               @@@@ Action for menu key μm
1e3
"Micron"
AVIEW
RTN
LBL 18               @@@@ Action for menu key mil
3.9370078740157e1
"mil (1/1000 in)"
├""
AVIEW
RTN
LBL 19               @@@@ Action for menu key cm
1e-2
RTN
LBL 20               @@@@ Action for menu key in
3.9370078740157e-2
"Inch"
AVIEW
RTN
LBL 21               @@@@ Action for menu key cm
1
RTN
LBL 22               @@@@ Action for menu key in
0.39370078740157
"Intl Inch"
AVIEW
RTN
LBL 23               @@@@ Action for menu key ft
0.3048
"Intl Foot"
AVIEW
RTN
LBL 24               @@@@ Action for menu key m
1e-3
RTN
LBL 25               @@@@ Action for menu key yd
0.032808398950131
"Intl Yard"
AVIEW
RTN
LBL 26               @@@@ Action for menu key km
1
RTN
LBL 27               @@@@ Action for menu key mi
0.62137119223733
"Int Mile"
AVIEW
RTN
LBL 28               @@@@ Action for menu key us mi
0.62136994949495
"US Mile"
AVIEW
RTN
LBL 29               @@@@ Action for menu key nmi
0.53995680345572
"Int Nautical mi"
├""
AVIEW
RTN
LBL 30               @@@@ Action for menu key m
1e3
RTN
LBL 31               @@@@ Action for menu key ft
3280.8398950131
"Intl Foot"
AVIEW
RTN
LBL 32               @@@@ Action for menu key hector
1
"hector"
AVIEW
RTN
LBL 33               @@@@ Action for menu key acre
2.4710538146717
"Int Acre"
AVIEW
RTN
LBL 34               @@@@ Action for menu key m^2
10000
RTN
LBL 35               @@@@ Action for menu key yd^2
11959.900463011
RTN
LBL 37               @@@@ Action for menu key l
1
RTN
LBL 38               @@@@ Action for menu key qt
1.0566882049662
"US Lq Quart"
AVIEW
RTN
LBL 39               @@@@ Action for menu key gal
0.26417205124156
"US Lq Gal"
AVIEW
RTN
LBL 40               @@@@ Action for menu key cc
1e3
RTN
LBL 41               @@@@ Action for menu key gal
1
"Gal"
AVIEW
RTN
LBL 42               @@@@ Action for menu key qt
4
"Quart"
AVIEW
RTN
LBL 43               @@@@ Action for menu key pint
8
"Pint"
AVIEW
RTN
LBL 44               @@@@ Action for menu key cup
16
"Cup"
AVIEW
RTN
LBL 45               @@@@ Action for menu key flOZ
128
"fl oz"
AVIEW
RTN
LBL 46               @@@@ Action for menu key tbsp
256
"Tablespoon"
AVIEW
RTN
LBL 47               @@@@ Action for menu key tsp
768
"Teaspoon"
AVIEW
RTN
LBL 49               @@@@ Action for menu key sec
1
RTN
LBL 50               @@@@ Action for menu key min
60
RTN
LBL 51               @@@@ Action for menu key hour
3600
RTN
LBL 52               @@@@ Action for menu key day
86400
RTN
LBL 53               @@@@ Action for menu key week
604800
RTN
LBL 54               @@@@ Action for menu key year
31536000
"365 day year"
AVIEW
RTN
LBL 55               @@@@ Action for menu key day
1
RTN
LBL 56               @@@@ Action for menu key year
365
RTN
LBL 57               @@@@ Action for menu key greg
365.2425
RTN
LBL 58               @@@@ Action for menu key julian
365.25
RTN
LBL 59               @@@@ Action for menu key astro
365.256363004
RTN
LBL 61               @@@@ Action for menu key kg
1
RTN
LBL 62               @@@@ Action for menu key lb
2.2046226218488
"Pound Int"
AVIEW
RTN
LBL 63               @@@@ Action for menu key g
1e3
RTN
LBL 64               @@@@ Action for menu key ozWT
35.27396194958
"Ounce Weight"
AVIEW
RTN
LBL 65               @@@@ Action for menu key ozTr
32.150746568628
"Ounce Troy"
AVIEW
RTN
LBL 66               @@@@ Action for menu key stone
0.15747304441777
"UK Stone"
AVIEW
RTN
LBL 67               @@@@ Action for menu key kg
1
RTN
LBL 68               @@@@ Action for menu key ton
0.001
"Metric Ton"
AVIEW
RTN
LBL 69               @@@@ Action for menu key US ton
1.10231131471e-3
"US (short) Ton"
AVIEW
RTN
LBL 70               @@@@ Action for menu key UK ton
9.84206530988e-4
"UK (long) Ton"
AVIEW
RTN
LBL 71               @@@@ Action for menu key N
1
RTN
LBL 72               @@@@ Action for menu key kgf
9.80665
RTN
LBL 73               @@@@ Action for menu key lbf
4.4482216153
"Int Pound Force"
├""
AVIEW
RTN
LBL 74               @@@@ Action for menu key m/s
1
RTN
LBL 75               @@@@ Action for menu key mph
0.44704
"Int Mi per hour"
├""
AVIEW
RTN
LBL 76               @@@@ Action for menu key kph
0.2777777778
RTN
LBL 77               @@@@ Action for menu key knot
0.5144444444
"International"
AVIEW
RTN
LBL 78               @@@@ Action for menu key Pa
1
"N/m^2"
AVIEW
RTN
LBL 79               @@@@ Action for menu key bar
100000
RTN
LBL 80               @@@@ Action for menu key psi
6894.7572932
RTN
LBL 81               @@@@ Action for menu key atm
101325
RTN
LBL 82               @@@@ Action for menu key mmHg
133.322
RTN
LBL 83               @@@@ Action for menu key inHg
133.322
RTN
LBL 84               @@@@ Action for menu key watt
1
RTN
LBL 85               @@@@ Action for menu key BTU/h
0.2930710702
"International"
AVIEW
RTN
LBL 86               @@@@ Action for menu key hp
735.49875
"Metric"
AVIEW
RTN
LBL 87               @@@@ Action for menu key kcal/h
1.163
RTN
LBL 88               @@@@ Action for menu key J/h
0.0002777778
RTN
LBL 89               @@@@ Action for menu key C→F
9
×
5
÷
32
+
RTN
LBL 90               @@@@ Action for menu key F→C
32
-
5
×
9
÷
RTN
LBL 91               @@@@ Action for menu key K→C
273.15
-
RTN
LBL 92               @@@@ Action for menu key C→K
273.15
+
RTN
@@@@ Free labels start at: 93
#+end_src
